[mode_keys]
d = 'DDR'
i = 'ITG'
e = '__exit'  # for exiting. not a real mode

# Use full paths
[GamePath]
# Use single quotes for Windows paths with \ slashes
path = ' ... ITGmania.exe'

# Add a new [[files]] block for each file you want to modify
[[files]]
path = ' ... AppData\Roaming\ITGmania\Save\Preferences.ini'
[files.settings]
FullscreenIsBorderlessWindow = "1"

[[files]]  
path = ' ... AppData\Roaming\ITGmania\Themes\Simply Love\Scripts\SL_Init.lua'
mode_required = true  # supply for mode specific behavior
[files.replacement]
replacement_path = ' ... AppData\Roaming\ITGmania\Themes\Simply Love\Scripts\__{mode}__SL_Init.lua'  # {mode} will be replaced with selected mode

[[files]]  # add dir to recursively modify files
path = 'Simply Love UserPrefs.ini'
dir = ' ... AppData\Roaming\ITGmania\Save\LocalProfiles'
mode_required = true
[files.settings.DDR]
NoteSkin = 'sch-ddr'  # NoteSkin name is all lower case
ShowExScore = 'false'
ShowFaPlusPane = 'false'
ShowFaPlusWindow = 'false'
[files.settings.ITG]
NoteSkin = 'devcel-ecfa'
ShowExScore = 'true'
ShowFaPlusPane = 'true'
ShowFaPlusWindow = 'true'

[[files]]
path = ' ... AppData\Roaming\ITGmania\Songs'  # Game songs location
mode_required = true
[files.link]
target_path = ' ... Songs\{mode}'  # Real songs location