[mode_keys]
d = 'DDR'
i = 'ITG'
e = '__exit'  # for exiting. not a real mode


[GamePath]
# Use single quotes for Windows paths with \ slashes
path = 'C:\Games\ITGmania\Program\ITGmania.exe'

# Add a new [[files]] block for each file you want to modify
[[files]]
path = 'C:\Users\Hojin\AppData\Roaming\ITGmania\Save\Preferences.ini'
[files.settings]
FullscreenIsBorderlessWindow = "1"

[[files]]  
path = 'C:\Users\Hojin\AppData\Roaming\ITGmania\Themes\Simply Love\Scripts\SL_Init.lua'
mode_required = true  # supply for mode specific behavior
[files.replacement]
replacement_path = 'C:\Users\Hojin\AppData\Roaming\ITGmania\Themes\Simply Love\Scripts\__{mode}__SL_Init.lua'  # {mode} will be replaced with selected mode

[[files]]  # add dir to recursively modify files
path = 'Simply Love UserPrefs.ini'
dir = 'C:\Users\Hojin\AppData\Roaming\ITGmania\Save\LocalProfiles'
mode_required = true
[files.settings.DDR]
NoteSkin = 'sch-ddr'
ShowExScore = 'false'
ShowFaPlusPane = 'false'
ShowFaPlusWindow = 'false'
[files.settings.ITG]
NoteSkin = 'devcel-ecfa'
ShowExScore = 'true'
ShowFaPlusPane = 'true'
ShowFaPlusWindow = 'true'

[[files]]
path = 'C:\Users\Hojin\AppData\Roaming\ITGmania\Songs'
mode_required = true
[files.link]
target_path = 'C:\Users\Hojin\Documents\StepmaniaAssets\Songs\{mode}'

#[[files]]
#path = 'Stats.xml'
#dir = 'C:\Users\Hojin\AppData\Roaming\ITGmania\Save\LocalProfiles'
#[files.matchreplace]
#until = '</GeneralData>'  # Read file until. Optional
#[[files.matchreplace.list]]  # Add more of these to regex match replace more things
#match = '(?s)<DefaultModifiers>(.+?)</DefaultModifiers>'
#replace = '<DefaultModifiers></DefaultModifiers>'

#[[files]]
#path = 'Casual-Stats.xml'
#dir = 'C:\Users\Hojin\AppData\Roaming\ITGmania\Save\LocalProfiles'
#[files.matchreplace]
#until = '</GeneralData>'
#[[files.matchreplace.list]]
#match = '(?s)<DefaultModifiers>(.+?)</DefaultModifiers>'
#replace = '<DefaultModifiers></DefaultModifiers>'
